### PR TITLE
fix-147 - Fix getting file for storage name with complex path

### PR DESCRIPTION
**Pull request by LucianDeveloper**

### CODE REVIEW

**Review by jowilf — CHANGES_REQUESTED** [review]
Thanks for the fix. Can we add a test case to ensure this won't break again in the future?

**Comment by NickNaskida** [comment]
@LucianDeveloper Hey, any updates regarding this?

**Comment by NickNaskida** [comment]
@jowilf Can we somehow get this merged? If not how can I help to merge this in? Should I create a new pull request with this feature and test case?

**Comment by jowilf** [comment]
@NickNaskida, we need a simple test case. I haven't had the time to work on it myself yet. The quickest way to merge it is to create another PR with a test case, as you can't commit to this branch directly.

**Comment by NickNaskida** [comment]
Just did that, please take a look once you have time. Thanks!

**Comment by jowilf** [comment]
this is now implemented in #154

**Pull request closed without merging**
